# Generated by Django 3.0.3 on 2020-07-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
