# Generated by Django 3.0.3 on 2020-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Aadhaar_number',
            field=models.IntegerField(default=0),
        ),
    ]
