# Generated by Django 3.0.3 on 2020-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0005_auto_20200729_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=128),
        ),
    ]
