# Generated by Django 3.0.3 on 2020-07-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0008_auto_20200729_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
