# Generated by Django 3.0.3 on 2020-07-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0010_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
